apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: myapp-ns
  labels:
    app: nginx
  annotations:
    managed-by: Helm
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    events {
        worker_connections  1024;
    }

    http {
        # Proxy cache settings
        proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m;

        server {
            listen 443 ssl;
            server_name example.com;

            ssl_certificate     /etc/nginx/certs/tls.crt;
            ssl_certificate_key /etc/nginx/certs/tls.key;

            location / {
                proxy_pass http://app-service.myapp-ns.svc.cluster.local;
                proxy_set_header Host $host;
                proxy_cache my_cache;
                proxy_cache_valid 200 1m;
            }
        }
    }
