apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.containerPort }}
  type: ClusterIP
